name: Build the site
on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6

      - run: |
          npm ci
          npm run build
        env:
          VITE_BASE: ${{ steps.pages.outputs.base_path }}

      - name: Sanitize referrer policy
        run: |
          ZIP="https://github.com/altbdoor/clean-links/releases/latest/download/clean-links-linux.tgz"
          curl --remote-name --location "$ZIP"
          tar xzf clean-links-linux.tgz
          ./clean-links run --fix-all ./dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
